version: 1.2
workflows:
  - name: rare-variant-enrichment
    subclass: WDL
    primaryDescriptorPath: /workflows/rare_variant_enrichment.wdl
  - name: extract-variant-carriers
    subclass: WDL
    primaryDescriptorPath: /workflows/extract_variant_carriers.wdl
  - name: multiomics-outliers
    subclass: WDL
    primaryDescriptorPath: /workflows/multiomics_outliers.wdl
