name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "envs/Dockerfile"
      - "pyproject.toml"
      - "scripts/**"
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/docker-image.yml"
      - "envs/Dockerfile"
      - "pyproject.toml"
      - "scripts/**"
      - "src/**"
      - "tests/**"


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Log in to ghcr.io with docker
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and optionally push docker container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./envs/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
